/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nng_android_NngWrapper */

#ifndef _Included_com_nng_android_NngWrapper
#define _Included_com_nng_android_NngWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPair0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPair0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPair1Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPair1Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngReq0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngReq0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngRep0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngRep0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPub0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPub0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSub0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngSub0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPush0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPush0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPull0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPull0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngBus0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngBus0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngListen
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngListen
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngDial
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngDial
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSend
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSend
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngRecv
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngRecv
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSetRecvTimeout
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSetRecvTimeout
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSetSendTimeout
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSetSendTimeout
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngGetRecvTimeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngGetRecvTimeout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngGetSendTimeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngGetSendTimeout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSubSubscribe
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSubSubscribe
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSubUnsubscribe
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSubUnsubscribe
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSocketId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSocketId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngStrerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nng_android_NngWrapper_nngStrerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nng_android_NngWrapper_nngVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSurveyor0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngSurveyor0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngRespondent0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngRespondent0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngAioAlloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngAioAlloc
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngAioFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nng_android_NngWrapper_nngAioFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSocketSendAio
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_nng_android_NngWrapper_nngSocketSendAio
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSocketRecvAio
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_nng_android_NngWrapper_nngSocketRecvAio
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngAioResult
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngAioResult
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngAioWait
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nng_android_NngWrapper_nngAioWait
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngMsgAlloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngMsgAlloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngMsgFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nng_android_NngWrapper_nngMsgFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngMsgBody
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nng_android_NngWrapper_nngMsgBody
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngMsgLen
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngMsgLen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSendMsg
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSendMsg
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngRecvMsg
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngRecvMsg
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngUrlParse
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngUrlParse
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngUrlFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nng_android_NngWrapper_nngUrlFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngUrlScheme
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nng_android_NngWrapper_nngUrlScheme
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngUrlHost
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nng_android_NngWrapper_nngUrlHost
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngUrlPort
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nng_android_NngWrapper_nngUrlPort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngDialerCreate
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngDialerCreate
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngListenerCreate
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngListenerCreate
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngDialerStart
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngDialerStart
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngListenerStart
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngListenerStart
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngDialerClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngDialerClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngListenerClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngListenerClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngStatsGet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngStatsGet
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngStatsFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nng_android_NngWrapper_nngStatsFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngStatName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nng_android_NngWrapper_nngStatName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngStatValue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngStatValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngStatNext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngStatNext
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
