/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nng_android_NngWrapper */

#ifndef _Included_com_nng_android_NngWrapper
#define _Included_com_nng_android_NngWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPair0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPair0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPair1Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPair1Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngReq0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngReq0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngRep0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngRep0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPub0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPub0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSub0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngSub0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPush0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPush0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngPull0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngPull0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngBus0Open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nng_android_NngWrapper_nngBus0Open
  (JNIEnv *, jobject);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngListen
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngListen
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngDial
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngDial
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSend
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSend
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngRecv
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngRecv
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSetRecvTimeout
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSetRecvTimeout
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSetSendTimeout
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSetSendTimeout
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngGetRecvTimeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngGetRecvTimeout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngGetSendTimeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngGetSendTimeout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSubSubscribe
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSubSubscribe
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSubUnsubscribe
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSubUnsubscribe
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngSocketId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nng_android_NngWrapper_nngSocketId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngStrerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nng_android_NngWrapper_nngStrerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nng_android_NngWrapper
 * Method:    nngVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nng_android_NngWrapper_nngVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
